apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cell-poc.fullname" . }}-config
  labels:
    {{- include "cell-poc.labels" . | nindent 4 }}
data:
  cell: {{ include "cell-poc.cell" . | quote }}
  greeting: "Hello from cell {{ include "cell-poc.cell" . }}"
